### ISSUE TITLE
handleShowToast未定义

### ISSUE THREAD

**Issue by hi-noikiy** [xinlc/uniapp-vue3-ts-template#1]
页面初次加载的时候，使用usePageStore().showToast是可以正常调用的，但是从其他页面跳转回来的时候，再去调用showToast就会提示handleShowToast为定义

**Comment by xinlc** [comment]
生命周期问题，试一下修改 [UBasePage.vue](https://github.com/xinlc/uniapp-vue3-ts-template/blob/main/src/components/UnoUI/UBasePage/UBasePage.vue#L26) 代码如下：
```js
  onMounted(() => {
    _notifyRef.value = notifyRef.value;
    _toastRef.value = toastRef.value;
  });

  onShow(() => {
    _notifyRef.value = notifyRef.value;
    _toastRef.value = toastRef.value;
  });

  onHide(() => pageReset());
```

**Comment by hi-noikiy** [comment]
好，我晚点试试，奇怪的是其他页面这样来回跳转都没问题。

**Comment by hi-noikiy** [comment]
@xinlc 测试无效。如果页面是使用router.push之类跳转的就没问题。如果是用navigateBack或者其他方式后退的话，就会出现未定义

**Comment by xinlc** [comment]
> @xinlc 测试无效。如果页面是使用router.push之类跳转的就没问题。如果是用navigateBack或者其他方式后退的话，就会出现未定义

我测试没问题，提供个复现 Demo？我试一下

**Comment by hi-noikiy** [comment]
@xinlc 有联系方式吗？或者你可以加我微信atxiner，有项目合作
